# Generated by Django 2.2.1 on 2019-05-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoes',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.product',),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Vizzano', max_length=120),
            preserve_default=False,
        ),
    ]
