# Generated by Django 2.2.1 on 2019-05-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190511_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('SH', 'Shoes'), ('CL', 'Clothing'), ('BA', 'Bags')], default='SH', max_length=2),
            preserve_default=False,
        ),
    ]
