# Generated by Django 2.2.1 on 2019-05-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190512_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='productImg/default.jpg', upload_to='productImg/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.DeleteModel(
            name='Shoes',
        ),
        migrations.CreateModel(
            name='Shoes',
            fields=[
            ],
            options={
                'verbose_name': 'Shoes',
                'verbose_name_plural': 'Shoes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.product',),
        ),
    ]
