# Generated by Django 2.2.1 on 2019-05-12 21:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_product_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), default=['#ef562f', '#43750e', '#40967f', '#060707', '#f2f3f9'], size=10),
            preserve_default=False,
        ),
    ]
