# Generated by Django 2.2.1 on 2019-05-13 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190512_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(max_length=200, upload_to='static/productImg/'),
        ),
    ]
